# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Model.proto',
  package='BlockData',
  serialized_pb=_b('\n\x0bModel.proto\x12\tBlockData\"\x9b\x01\n\x05Model\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\r\n\x05sizeX\x18\x02 \x02(\x05\x12\r\n\x05sizeY\x18\x03 \x02(\x05\x12\r\n\x05sizeZ\x18\x04 \x02(\x05\x12\x0e\n\x06pivotX\x18\x05 \x02(\x05\x12\x0e\n\x06pivotY\x18\x06 \x02(\x05\x12\x0e\n\x06pivotZ\x18\x07 \x02(\x05\x12$\n\x06\x62locks\x18\x08 \x03(\x0b\x32\x14.BlockData.BlockPair\")\n\tBlockPair\x12\x0e\n\x06lenght\x18\x01 \x02(\x05\x12\x0c\n\x04type\x18\x02 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='BlockData.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='BlockData.Model.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sizeX', full_name='BlockData.Model.sizeX', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sizeY', full_name='BlockData.Model.sizeY', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sizeZ', full_name='BlockData.Model.sizeZ', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pivotX', full_name='BlockData.Model.pivotX', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pivotY', full_name='BlockData.Model.pivotY', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pivotZ', full_name='BlockData.Model.pivotZ', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blocks', full_name='BlockData.Model.blocks', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=182,
)


_BLOCKPAIR = _descriptor.Descriptor(
  name='BlockPair',
  full_name='BlockData.BlockPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lenght', full_name='BlockData.BlockPair.lenght', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='BlockData.BlockPair.type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=225,
)

_MODEL.fields_by_name['blocks'].message_type = _BLOCKPAIR
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['BlockPair'] = _BLOCKPAIR

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'Model_pb2'
  # @@protoc_insertion_point(class_scope:BlockData.Model)
  ))
_sym_db.RegisterMessage(Model)

BlockPair = _reflection.GeneratedProtocolMessageType('BlockPair', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKPAIR,
  __module__ = 'Model_pb2'
  # @@protoc_insertion_point(class_scope:BlockData.BlockPair)
  ))
_sym_db.RegisterMessage(BlockPair)


# @@protoc_insertion_point(module_scope)
