//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Model.proto
namespace BlockData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Model")]
  public partial class Model : global::ProtoBuf.IExtensible
  {
    public Model() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _sizeX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sizeX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sizeX
    {
      get { return _sizeX; }
      set { _sizeX = value; }
    }
    private int _sizeY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sizeY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sizeY
    {
      get { return _sizeY; }
      set { _sizeY = value; }
    }
    private int _sizeZ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sizeZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sizeZ
    {
      get { return _sizeZ; }
      set { _sizeZ = value; }
    }
    private int _pivotX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pivotX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pivotX
    {
      get { return _pivotX; }
      set { _pivotX = value; }
    }
    private int _pivotY;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"pivotY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pivotY
    {
      get { return _pivotY; }
      set { _pivotY = value; }
    }
    private int _pivotZ;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"pivotZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pivotZ
    {
      get { return _pivotZ; }
      set { _pivotZ = value; }
    }
    private readonly global::System.Collections.Generic.List<BlockData.BlockPair> _blocks = new global::System.Collections.Generic.List<BlockData.BlockPair>();
    [global::ProtoBuf.ProtoMember(8, Name=@"blocks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BlockData.BlockPair> blocks
    {
      get { return _blocks; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlockPair")]
  public partial class BlockPair : global::ProtoBuf.IExtensible
  {
    public BlockPair() {}
    
    private int _lenght;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lenght", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lenght
    {
      get { return _lenght; }
      set { _lenght = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}